version: '3'

services:
  db:
    image: postgres
  web:
    image: adeleh/djangoapp
    command: python2 ./testdockerdjango/manage.py runserver 0.0.0.0:8000
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    volumes:
      - .:/django
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - webnet
networks:
  webnet:
