version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx01
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
    networks:
      - webnet
  db:
    image: postgres:latest
    container_name: db01
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
  web:
    image: adeleh/djangoapp2
    container_name: web01
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - webnet
networks:
  webnet:
